(()=>{
'use strict';
const cache=new Map(), DB='mentor-course-assets-v1', STORE='bundles';
const td=new TextDecoder();
function mime(name){const e=name.toLowerCase().split('.').pop();return ({pdf:'application/pdf',txt:'text/plain;charset=utf-8',sql:'text/plain;charset=utf-8',csv:'text/csv;charset=utf-8',json:'application/json',md:'text/markdown;charset=utf-8',html:'text/html;charset=utf-8',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',xls:'application/vnd.ms-excel',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',ipynb:'application/x-ipynb+json',zip:'application/zip'})[e]||'application/octet-stream'}
function u16(d,o){return d.getUint16(o,true)} function u32(d,o){return d.getUint32(o,true)}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function idbGet(k){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)})}
async function idbPut(k,v){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>ok(true);r.onerror=()=>no(r.error)})}
async function idbDel(k){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).delete(k);r.onsuccess=()=>ok(true);r.onerror=()=>no(r.error)})}
const key=()=>window.MENTOR_CONFIG?.id||location.pathname;
async function importZip(){return new Promise((resolve,reject)=>{const i=document.createElement('input');i.type='file';i.accept='.zip,application/zip';i.onchange=async()=>{try{const f=i.files?.[0];if(!f)return reject(new Error('No course ZIP selected'));const buf=await f.arrayBuffer();const course=window.MENTOR_CONFIG?.getCourse?.()||[];const probes=course.flatMap(p=>[p.artifacts?.lesson,p.artifacts?.practice]).filter(Boolean).slice(0,8);let valid=false;for(const x of probes){try{findEntry(buf,x);valid=true;break}catch{}}if(!valid)throw new Error('This ZIP does not contain this Mentor’s canonical course files. Select the matching current course package.');await idbPut(key(),{name:f.name,bytes:buf,storedAt:Date.now()});cache.set('local:'+key(),buf);resolve({name:f.name,bytes:buf})}catch(e){reject(e)}};i.click()})}
async function localBundle(){const ck='local:'+key();if(cache.has(ck))return cache.get(ck);const v=await idbGet(key());if(!v?.bytes)return null;cache.set(ck,v.bytes);return v.bytes}
async function loadBundle(spec){const k=Array.isArray(spec)?spec.join('|'):String(spec);if(cache.has(k))return cache.get(k);const p=(async()=>{if(Array.isArray(spec)){const texts=await Promise.all(spec.map(async url=>{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`Asset part ${r.status}: ${url}`);return (await r.text()).trim()}));const b64=texts.join(''),bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a.buffer}const r=await fetch(spec,{cache:'no-store'});if(!r.ok)throw new Error(`Asset bundle ${r.status}: ${spec}`);return r.arrayBuffer()})();cache.set(k,p);return p}
function cleanWant(want){return String(want).replace(/^\.\.\//,'').replace(/^\.\//,'').replace(/^\//,'')}
function findEntry(buf,want){const a=new Uint8Array(buf),d=new DataView(buf);let e=-1;for(let i=a.length-22;i>=Math.max(0,a.length-65557);i--){if(u32(d,i)===0x06054b50){e=i;break}}if(e<0)throw new Error('ZIP end directory not found');const count=u16(d,e+10),cd=u32(d,e+16);let p=cd;want=cleanWant(want);for(let i=0;i<count;i++){if(u32(d,p)!==0x02014b50)throw new Error('Invalid ZIP central directory');const method=u16(d,p+10),csize=u32(d,p+20),usize=u32(d,p+24),nlen=u16(d,p+28),xlen=u16(d,p+30),clen=u16(d,p+32),loff=u32(d,p+42),name=td.decode(a.slice(p+46,p+46+nlen));if(name===want||name.endsWith('/'+want)){if(u32(d,loff)!==0x04034b50)throw new Error('Invalid ZIP local header');const ln=u16(d,loff+26),lx=u16(d,loff+28),start=loff+30+ln+lx;return {name,method,csize,usize,bytes:a.slice(start,start+csize)}}p+=46+nlen+xlen+clen}throw new Error(`Course asset not found: ${want}`)}
async function unpack(entry){if(entry.method===0)return entry.bytes;if(entry.method===8&&'DecompressionStream'in window){const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([entry.bytes]).stream().pipeThrough(ds)).arrayBuffer())}throw new Error(`Unsupported ZIP compression method ${entry.method}`)}
function show(bytes,name){const type=mime(name),blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),ext=name.toLowerCase().split('.').pop();if(['pdf','txt','sql','csv','json','md','html','ipynb'].includes(ext)){const w=window.open(url,'_blank','noopener');if(!w){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click()}}else{const a=document.createElement('a');a.href=url;a.download=name.split('/').pop();document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),120000)}
async function resolveBundle(phase){const spec=phase?.assetBundleParts||phase?.assetBundle||window.MENTOR_CONFIG?.assetBundleParts||window.MENTOR_CONFIG?.assetBundle;if(spec){try{return await loadBundle(spec)}catch(e){console.warn('Hosted course asset unavailable; trying device course bundle',e)}}let b=await localBundle();if(b)return b;if(!confirm('Course files are not connected on this device yet. Choose the matching canonical course ZIP once so Mentor can open Teaching Books, Practice, Reviews and Gates directly.'))throw new Error('Course files not connected');await importZip();b=await localBundle();if(!b)throw new Error('Course ZIP import failed');return b}
window.COURSE_ASSETS_OPEN=async(path,label,phase)=>{const buf=await resolveBundle(phase);const entry=findEntry(buf,path);const bytes=await unpack(entry);show(bytes,entry.name);return true};
window.COURSE_ASSETS_IMPORT=importZip;
window.COURSE_ASSETS_STATUS=async()=>{const v=await idbGet(key());return v?{connected:true,name:v.name,storedAt:v.storedAt}:{connected:false}};
window.COURSE_ASSETS_FORGET=async()=>{cache.delete('local:'+key());await idbDel(key())};
window.COURSE_ASSETS_CHECK=async(path,phase)=>{const buf=await resolveBundle(phase);findEntry(buf,path);return true};
})();
