(()=>{
  function ensure(){if(!D.skippedUnits||typeof D.skippedUnits!=='object')D.skippedUnits={}}
  function isSkipped(stage,i){ensure();return !!(D.skippedUnits[stage.id]&&D.skippedUnits[stage.id][i])}
  function setSkipped(stage,i,v){ensure();if(!D.skippedUnits[stage.id])D.skippedUnits[stage.id]={};if(v)D.skippedUnits[stage.id][i]=true;else delete D.skippedUnits[stage.id][i]}
  const baseNextAction=nextAction;
  nextAction=function(){const s=cur(),a=up(s),p=pp(s),i=a.findIndex((x,idx)=>!x&&!isSkipped(s,idx));if(i>=0){const u=s.plan[i];return `<b>Next:</b> ${esc(u.id)} — ${esc(u.label)}.<br><span class="small">Lesson: ${esc(s.lesson)}<br>Practice: ${esc(s.practice)}<br>Load: ${esc(u.load)}</span>`}const skipped=a.map((x,idx)=>(!x&&isSkipped(s,idx))?idx:-1).filter(i=>i>=0);if(skipped.length)return `<b>All currently unskipped lesson units are done.</b><br><span class="small">${skipped.length} lesson unit${skipped.length>1?'s are':' is'} still marked <b>Skipped for now</b>. Resume and finish ${skipped.length>1?'them':'it'} before this phase can pass its Gate.</span>`;return baseNextAction()}
  const baseRebuild=rebuildTasks;
  rebuildTasks=function(){const s=cur(),a=up(s),p=pp(s),out=[],i=a.findIndex((x,idx)=>!x&&!isSkipped(s,idx)),j=p.findIndex(x=>!x),base=Date.now();if(i>=0){const u=s.plan[i];out.push({id:base+1,text:`${u.id}: ${u.label} — lesson + matching practice`,stage:s.id,pom:u.load==='Heavy'?6:u.load==='Light'?2:4,done:false,auto:true})}else{const skipped=a.map((x,idx)=>(!x&&isSkipped(s,idx))?idx:-1).filter(i=>i>=0);if(skipped.length)out.push({id:base+1,text:`Return to ${s.plan[skipped[0]].id}: ${s.plan[skipped[0]].label} — previously skipped`,stage:s.id,pom:2,done:false,auto:true})}if(j>=0)out.push({id:base+2,text:`Evidence: ${s.steps[j]}`,stage:s.id,pom:2,done:false,auto:true});out.push({id:base+3,text:'No-tutorial recall: explain today’s concept and one validation check aloud',stage:s.id,pom:1,done:false,auto:true});D.tasks=D.tasks.filter(t=>!t.auto).concat(out);save();renderTasks()}
  function decorate(){ensure();const s=cur(),a=up(s),rows=[...document.querySelectorAll('#schedule [data-unit]')];rows.forEach(input=>{const i=+input.dataset.unit,row=input.closest('.item');if(!row)return;const done=!!a[i],skipped=!done&&isSkipped(s,i);if(skipped){row.style.opacity='.72';row.dataset.skipped='true'}else{row.style.opacity='';delete row.dataset.skipped}let wrap=row.querySelector('.lessonSkipWrap');if(!wrap){wrap=document.createElement('div');wrap.className='lessonSkipWrap';wrap.style.cssText='display:flex;gap:6px;align-items:center;margin-left:8px;flex-wrap:wrap';row.appendChild(wrap)}wrap.innerHTML='';if(skipped){const pill=document.createElement('span');pill.className='pill';pill.textContent='Skipped for now';wrap.appendChild(pill)}const b=document.createElement('button');b.type='button';b.className='btn ghost';b.textContent=done?'Completed':skipped?'Resume lesson':'Skip for now';b.disabled=done;b.onclick=e=>{e.preventDefault();e.stopPropagation();setSkipped(s,i,!skipped);save();render()};wrap.appendChild(b);const old=input.onchange;input.onchange=e=>{if(e.target.checked)setSkipped(s,i,false);if(old)old(e)}})}
  const baseRender=render;render=function(){baseRender();decorate()};
  ensure();
})();
